name: redarx_flutter_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  redarx:
    git: git://github.com/rxlabz/redarx
  http:
  built_value: ^2.1.0

dev_dependencies:
  build: ^0.9.0
  build_runner: ^0.3.2
  built_value_generator: ^2.1.0
  source_gen: ^0.7.0
  quiver: '>=0.21.0 <0.26.0'
  flutter_test:
    sdk: flutter
  built_collection: ^1.5.0
  firebase_database: "^0.0.14"

flutter:

  uses-material-design: true
